# Generated by Django 2.2 on 2019-04-29 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20190429_1000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='created_at',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='task',
            name='due_on',
            field=models.DateField(),
        ),
    ]
